from django.urls import path
from . import views
urlpatterns = [
    path('',views.index, name="index"),
    path('add-billing',views.addbilling, name="addbilling"),
    path('add-prescription',views.addprescription, name="addprescription"),
    path('appointments',views.appointments,name="appointments"),
    path('blank-page',views.blankpage, name="blankpage"),
    path('booking',views.booking, name="booking"),
    path('bookings/<int:bid>',views.bookings, name="bookings"),
    path('booking-success/<int:bid>',views.bookingsuccess, name="bookingsuccess"),
    path('calendar',views.calender, name="calender"),
    path('change-password',views.changepassword, name="changepassword"),
    path('chat',views.chat, name="chat"),
    path('chat-doctor',views.chatdoctor, name="chatdoctor"),
    path('checkout/<int:bid>',views.checkout, name="checkout"),
    path('checkouts/<int:bid>',views.checkouts, name="checkouts"),
    path('components',views.components, name="components"),
    path('doctor-change-password',views.doctorchangepassword, name="doctorchangepassword"),
    path('doctor-dashboard',views.doctordashboard, name="doctordashboard"),
    path('doctor-profile/<int:id>',views.doctorprofile, name="doctorprofile"),
    path('patient-profile/<int:id>',views.patientprofile, name="patientprofile"),
    path('doctor-profile-settings',views.doctorprofilesettings, name="doctorprofilesettings"),
    path('doctor-register',views.doctorregister, name="doctorregister"),
    path('edit-billing',views.editbilling, name="editbilling"),
    path('edit-prescription',views.editprescription, name="editprescription"),
    path('favourites',views.favourites, name="favourites"),
    path('forgot-password',views.forgotpassword, name="forgotpassword"),
    path('invoice-view/<int:bid>',views.invoiceview, name="invoiceview"),
    path('invoices',views.invoices, name="invoices"),
    path('patientslogin/<int:bid>',views.patientslogin,name="patientslogin"),
    path('patientlogins/<int:bid>',views.patientlogins,name="patientlogins"),
    path('websitelogin',views.websitelogin,name="websitelogin"),
    path('websitelogout',views.logouts,name="websitelogout"),
    path('my-patients',views.mypatients, name="mypatients"),
    path('patient-dashboard',views.patientdashboard, name="patientdashboard"),
    path('profile-settings',views.patientprofilesettings, name="patientprofilesettings"),
    path('privacy-policy',views.privacypolicy, name="privacypolicy"),
    path('patient-profile',views.patientprofile, name="patientprofile"),
    path('register',views.register,name="register"),
    path('register_doctor',views.register_doctor, name="register_doctor"),
    path('register_patient',views.register_patient, name="register_patient"),
    # path('reviews/<int:rid>',views.reviews, name="reviews"),
    path('recomend/<int:sid>/<str:str>',views.recomend, name="recomend"),
    path('schedule-timings',views.scheduletimings, name="scheduletimings"),
    path('search',views.search, name="search"),
    path('social-media',views.socialmedia, name="socialmedia"),
    path('term-condition',views.termcondition, name="termcondition"),
    path('video-call/<int:id>',views.videocall, name="videocall"),
    path('feed', views.feed, name = "feed"),
    path('voice-call',views.voicecall, name="voicecall"),
    path('stats/<int:id>/<str:str>',views.stats,name="stats")


]